### ISSUE TITLE
适用于android4.x系统，但不支持6.0和7.0

### ISSUE THREAD

**Issue by likky** [RuijiePan/FileManager#3]
经过测试，在android7.0真机上部分功能无法使用，包括分类中的音乐、图片、视频等页面都是空白，垃圾清理扫描出来点击清理直接应用崩溃等。

**Comment by RuijiePan** [comment]
android7.0音乐、图片、视频等页面是因为获取资源drawbale在7.0手机上或报错。代码里面使用的是getResources().getDrawable(ResourceId)；这是一个废弃的方法，改成ActivityCompat.getDrawable(contexd, ResourceId);即可获取音乐、图片、视频等。
扫描文件奔溃是因为获取系统缓存的时候没有做空指针处理。
我在本地已经处理过该问题了，只是代码还没同步。。。我明天更新下代码。你到时候再看看。

**Comment by likky** [comment]
好的，多谢大神

**Comment by RuijiePan** [comment]
7.0問題已經修復

**Comment by likky** [comment]
7.0以扫描出垃圾，但是清理时依然崩溃，无法清理。
你可以找台手机试试，我是荣耀6X
